Mobile and Desktop View Melody Capstone one project pull request
AleWaweru/Melody pull request #3
Opened 2023-04-27 14:14 UTC by AleWaweru

created both mobile and desktop versions

2023-04-27 19:59 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @AleWaweru 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment, so I can receive the notification or use Slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 19:59 UTC, iambenkis commented on home.html
> +
- [ ] Your design look great , but it could be better to update your background image so it looks exactly as in the given design 👍 

Your design

![Capture](https://user-images.githubusercontent.com/80458199/234966054-63f45235-4833-42d2-9bba-b13b2574250e.PNG)

Template design

![Capture 1](https://user-images.githubusercontent.com/80458199/234966113-2f4134a2-f839-4a92-a768-8d364ac39d20.PNG)

2023-04-27 19:59 UTC, iambenkis commented on home.html
> +            <h3>Grand Opening</h3>
- [ ] You are going to notice with me that whenever the user is hovering on these cards, it should render the `hover` property as sowed in on the image below

| Your design |  Template design |
| :---: | :---: |
| ![Capture](https://user-images.githubusercontent.com/80458199/234970451-edccd9c8-e237-413e-94c5-058e31d82e48.PNG) | ![Capture 1](https://user-images.githubusercontent.com/80458199/234970542-57590f09-5721-4525-9377-80ed9085936c.PNG) |

2023-04-27 19:59 UTC, iambenkis commented on script.js
> +    Description: 'Benkler studies commons-based peer production, and published his seminal book, The Wealth of Networks in 2006',
- [ ] Kindly make sure you implement the `see more` button that allows user to see more `speaker` or to see less speaker , when the user is in the mobile version 👍 

![Capture 5](https://user-images.githubusercontent.com/80458199/234972705-d0dfed1d-e62b-4509-b62c-9c88bdfc674e.PNG)

2023-04-27 19:59 UTC, iambenkis commented on home.html
> +    </div>
- [ ] Good job implementing the speaker section 👏 , but your desing does not stick to the template design , make sure the `chess` image is found on each `speaker` 👍 
- [ ] Also Kindly update the color of the `chess` as represented in the design 😄 

### Template design
![Capture 2](https://user-images.githubusercontent.com/80458199/234974454-770a562a-2953-46e2-b447-f97cb6716c02.PNG)

### Your design

![Capture 3](https://user-images.githubusercontent.com/80458199/234974486-863f3a07-8009-4cf1-884b-d9eeaa7f4440.PNG)

2023-04-27 19:59 UTC, iambenkis commented on home.html
> +      </div>
- [ ] Your footer looks great 👍 ,  it could be better if you arrange the two section as represented in the template design 👍 
- [ ] Make sure you respect background color of each section 👍 , `margin` , `padding` etc 👍 

### Your design 

![Capture](https://user-images.githubusercontent.com/80458199/234976470-c5475159-da59-451c-940e-a0d9d825ea8a.PNG)

### Template design 

![Capture 0](https://user-images.githubusercontent.com/80458199/234976528-d3cb0b4c-9172-4f25-ad10-db8c7dc18eb0.PNG)

2023-04-27 19:59 UTC, iambenkis commented on about.html
> +
- [ ] Kindly make sure the styling of this text stick to the design given in the Figma template. For a design to stick to another one , parameters like font should be the same , kindly update this font

| Your design | Template design |
| :---: | :---: |
| ![Capture](https://user-images.githubusercontent.com/80458199/234977197-ee1624c7-4482-4baf-89ff-97a71055938a.PNG) | ![Capture 2](https://user-images.githubusercontent.com/80458199/234977299-9b31f28d-e0d1-438e-9c3c-1b140dfad32b.PNG) |

2023-04-28 06:23 UTC, AleWaweru commented on home.html
> +      </div>
done

2023-04-28 20:25 UTC, AleWaweru commented on script.js
> +    Description: 'Benkler studies commons-based peer production, and published his seminal book, The Wealth of Networks in 2006',
done

2023-04-28 20:25 UTC, AleWaweru commented on home.html
> +            <h3>Grand Opening</h3>
done

2023-04-28 20:25 UTC, AleWaweru commented on home.html
> +
done

2023-04-28 20:25 UTC, AleWaweru commented on home.html
> +      </div>
done

2023-04-28 20:26 UTC, AleWaweru commented on home.html
> +
done

2023-04-28 20:26 UTC, AleWaweru commented on home.html
> +    </div>
done

2023-04-28 20:26 UTC, AleWaweru commented on about.html
> +
done

2023-04-29 00:39 UTC, codecaiine requested changes
Hi @AleWaweru , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good design ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 00:39 UTC, codecaiine commented on home.html
> +    </div>
- [ ] Good job so far but your heading is a bit different from the original as mentioned by the previous reviewer Please make sure that your headline section elements have the same `font size`, `color`, `height`, `width`, and spacing `padding/spacing` as defined in the original design. cause you need to stick the design as much as possible :+1: 

Check the screenshots below to compare and see the differences :point_down: 

####  Original design
![Screenshot from 2022-10-28 17-48-01](https://user-images.githubusercontent.com/6615394/198701404-f4138d1d-135f-4c01-aade-e1994a238fd1.jpg)

2023-04-29 00:39 UTC, codecaiine commented on home.html
> +        </div>
- [ ] Good job so far :clap: But I think there are a few things with your design you need to work on. Please make sure that when the topic card has hovered with the mouse you have a border around it like on the screenshot below and also your button has the same color as on the design. :+1: 

- [ ] Please make sure to have the same design, especially the space between your program card as defined on the original design :+1: 

#### Orignal design
![Template2](https://user-images.githubusercontent.com/6615394/210799135-2796a81c-2ff1-4950-9d6b-1f7687384658.jpg)

2023-04-29 00:39 UTC, codecaiine commented on README.md
> +https://www.loom.com/share/4380828fc79644a494eeeae5ecf7d19f
- [ ] Your video length is around 6 mins and the requirement is 5 mins max. As mentioned by the previous reviewer please record another where you talk about a piece of code that you are proud of which is very important as it shows your ability to explain technical concepts clearly. Please make sure that the video is 5 minutes max 👍 

> * [ ]   In your video presentation, you explained what is your website about and its features, but you forgot to mention a piece of code that you are proud of which is very important as it shows your ability to explain technical concepts clearly 😉. Please record another 5 minutes video and include that part too 😃 👍

2023-04-29 08:41 UTC, Ismailco approved these changes
### Hi @AleWaweru, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ No linter errors
✔️ Used GitHub Flow
✔️ Work documented professionally

## Optional suggestions
- [ ] [OPTIONAL] Nice work making changes requested by the previous reviewer, however, your project may need some work to show great in your portfolio, kindly make sure all the elements on the page are aligned properly, also kindly make sure that only the cards in the Program section change style on hover not all the elements of the card

![Screenshot_20230429_093219](https://user-images.githubusercontent.com/25227022/235293586-46dce1e0-1a68-44a3-b932-3672e4598af3.png)
![Screenshot_20230429_093243](https://user-images.githubusercontent.com/25227022/235293647-8894d9fc-6972-45eb-8e29-deb5a86e0b17.png)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 08:45 UTC, merged